kind = "web"
previewPath = "/"
title = "Yemenici"
version = "1.0.0"
id = "artifacts/yemenici"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25916

[services.development]
run = "pnpm --filter @workspace/yemenici run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/yemenici", "run", "build" ]
publicDir = "artifacts/yemenici/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25916"
BASE_PATH = "/"
